export enum AccessResource {
  USER = 'USER',
  AUTH = 'AUTH',
  MEMBERSHIP = 'MEMBERSHIP',
  CARD = 'CARD',
  CARD_ACCESSS = 'CARD_ACCESS',
  CARD_ACCESSS_RENEWAL = 'CARD_ACCESS_RENEWAL',
  BLOCK = 'BLOCK',
  /** List blocks */
  BLOCK_LIST = 'BLOCK_LIST',
  BLOCK_REVISION = 'BLOCK_REVISION',
  BLOCK_REVISION_LIST = 'BLOCK_REVISION_LIST',
  DEFAULT = 'DEFAULT',
}
